#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/dfe9c21c-ecd9-4b09-a85f-9b807deea304 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool right;
  bool down;
  bool up;
  bool left;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <Servo.h>
bool flag=true;
int x,y,period_1;
int pre_pos=0,curr_pos=0;

Servo myservo;
Servo servo_2;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(112200);
  pinMode(16,OUTPUT);//d0
  pinMode(5,OUTPUT);//d1
  pinMode(4,OUTPUT);//d2
  pinMode(0,OUTPUT);//d3
  pinMode(2,INPUT_PULLUP);//d4
  pinMode(14,OUTPUT);//d7
  pinMode(12,OUTPUT);//d8
  digitalWrite(14,HIGH);
  digitalWrite(12,HIGH);
 
  
  myservo.attach(13);
  servo_2.attach(15);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1200); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
   digitalWrite(14,HIGH);
   digitalWrite(12,HIGH); 
  
  
}

void onUpChange() {
  // Do something
  if(up)
  {
    if(myservo.read()==100)
    {
        for (int pos = 100; pos >= 0; pos -= 1) 
        { 
           myservo.write(pos);              
            delay(30);                      
         }
    }
    myservo.write(0); 
    Serial.println("up");
    digitalWrite(16,HIGH);
    digitalWrite(5,HIGH);
   
    
   
  }
 
  else{
      
     digitalWrite(16,LOW);
     digitalWrite(5,LOW);
     digitalWrite(4,LOW);
     digitalWrite(0,LOW);
    
  }
}


void onDownChange() {
  // Do something
   if(down)
  {
        if(myservo.read()==100)
    {
        for (int pos = 100; pos >= 0; pos -= 1) 
        { 
           myservo.write(pos);              
            delay(30);                      
         }
    }
    myservo.write(0);
    Serial.println("down");
    digitalWrite(4,HIGH);
    digitalWrite(0,HIGH);
     
  }
else
  {
     
     digitalWrite(16,LOW);
     digitalWrite(5,LOW);
     digitalWrite(4,LOW);
     digitalWrite(0,LOW);
   
  }
}


void onLeftChange() {
  // Do something
   if(left)
  {
    if(myservo.read()==0)
    {
         for (int pos = 0; pos <= 100; pos += 1) 
          { 
            myservo.write(pos);             
            delay(30);                       
         }
    }  
    myservo.write(100);     
    Serial.println("left");
    digitalWrite(16,HIGH);
    digitalWrite(4,HIGH);
    
  }
  else
  {
     
     digitalWrite(16,LOW);
     digitalWrite(5,LOW);
     digitalWrite(4,LOW);
     digitalWrite(0,LOW);
     
  }
}


void onRightChange() {
  // Do something
   if(right)
  {
     if(myservo.read()==0)
    {
         for (int pos = 0; pos <= 100; pos += 1) 
          { 
            myservo.write(pos);             
            delay(30);                       
         }
    }
     myservo.write(100);  
    Serial.println("right");
    digitalWrite(0,HIGH);
    digitalWrite(5,HIGH);
    
  }
else
  {
  
     digitalWrite(16,LOW);
     digitalWrite(5,LOW);
     digitalWrite(4,LOW);
     digitalWrite(0,LOW);
     
  }
}
void onNumChange() {
  // Do something
  x=num/10;
  y=num%10;
  if(!flag)
  {
     Serial.println(num);
       
              if(x==1)
                 {
                    int period = y*1000;
                    unsigned long time_now = 0;
                    time_now = millis();
                    while(millis() < time_now + period)
                          {
                            int a=digitalRead(2);
                            delay(10);
                            int b=digitalRead(2);
                            if(a==0 && b==0)
                               {
                                period_1=1000;
                                time_now=millis();
                                while(millis() < time_now + period_1)
                                  {
                                    digitalWrite(12,LOW);
                                    digitalWrite(14,HIGH);
                                    yield();
                                   }
                                   break;
                               }
                               else{
                                 //wait approx. [period] ms
                                 Serial.println("camera up");
                                 digitalWrite(14,LOW);
                                 digitalWrite(12,HIGH);
                                 yield();
                               }
                           }
      
                 }
             else if(x==-1)
                 {
                     int period = y*-1000;
                     unsigned long time_now = 0;
                     time_now = millis();
                     while(millis() < time_now + period)
                           {
                                  int a=digitalRead(2);
                                  delay(10);
                                  int b=digitalRead(2);
                                  if(a==0 && b==0){
                                   period_1=1000;
                                   time_now=millis();
                                    while(millis() < time_now + period_1)
                                      {
                                        digitalWrite(14,LOW);
                                        digitalWrite(12,HIGH);
                                         yield();
                                       }
                                       break;
                                  }
                                       else{
                                  //wait approx. [period] ms
                                   Serial.println("camera down");
                                   digitalWrite(12,LOW);
                                   digitalWrite(14,HIGH);
                                   yield();
                                       }
                           }
      
                 }
               else if(x==2)
               {
                curr_pos=y*10;
                if(curr_pos>pre_pos)
                {
                  for (int pos = pre_pos; pos <= curr_pos; pos += 1) 
                     { 
                       servo_2.write(pos); 
                       delay(30);                       
                     }
                }
                else
                {
                  for (int pos = pre_pos; pos >= curr_pos; pos -= 1) 
                     { 
                       servo_2.write(pos); 
                       delay(30);                       
                     }
                }
                pre_pos=curr_pos;
               }
               else
                 {
                        digitalWrite(14,HIGH);
                        digitalWrite(12,HIGH); 
                  }
          
  
     
  }
  flag=false;
  

}